/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type BookingId = bigint;
export type BookingResult = { 'ok' : BookingView } |
  { 'err' : string };
export type BookingStatus = { 'cancelled' : null } |
  { 'confirmed' : null };
export interface BookingView {
  'id' : BookingId,
  'status' : BookingStatus,
  'referenceNumber' : string,
  'dropoffDate' : Timestamp,
  'userId' : Principal,
  'createdAt' : Timestamp,
  'pickupDate' : Timestamp,
  'totalAmount' : bigint,
  'vehicleId' : VehicleId,
}
export interface CreateBookingInput {
  'dropoffDate' : Timestamp,
  'pickupDate' : Timestamp,
  'vehicleId' : VehicleId,
}
export interface CreateVehicleInput {
  'features' : Array<string>,
  'name' : string,
  'description' : string,
  'pricePerDay' : bigint,
  'imageUrl' : string,
  'category' : VehicleCategory,
}
export type Timestamp = bigint;
export interface UpdateVehicleInput {
  'id' : VehicleId,
  'features' : Array<string>,
  'name' : string,
  'description' : string,
  'available' : boolean,
  'pricePerDay' : bigint,
  'imageUrl' : string,
  'category' : VehicleCategory,
}
export type VehicleCategory = { 'car' : null } |
  { 'suv' : null } |
  { 'van' : null } |
  { 'truck' : null } |
  { 'motorcycle' : null };
export type VehicleId = bigint;
export interface VehicleView {
  'id' : VehicleId,
  'features' : Array<string>,
  'name' : string,
  'description' : string,
  'available' : boolean,
  'pricePerDay' : bigint,
  'imageUrl' : string,
  'category' : VehicleCategory,
}
export interface _SERVICE {
  'addVehicle' : ActorMethod<[CreateVehicleInput], VehicleView>,
  'cancelBooking' : ActorMethod<
    [BookingId],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'createBooking' : ActorMethod<[CreateBookingInput], BookingResult>,
  'deleteVehicle' : ActorMethod<
    [VehicleId],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'getVehicle' : ActorMethod<[VehicleId], [] | [VehicleView]>,
  'isAdmin' : ActorMethod<[], boolean>,
  'listAllBookings' : ActorMethod<[], Array<BookingView>>,
  'listVehicles' : ActorMethod<[], Array<VehicleView>>,
  'myBookings' : ActorMethod<[], Array<BookingView>>,
  'registerAdmin' : ActorMethod<[], { 'ok' : null } | { 'err' : string }>,
  'setVehicleAvailability' : ActorMethod<
    [VehicleId, boolean],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'updateVehicle' : ActorMethod<[UpdateVehicleInput], VehicleView>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];