/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const VehicleCategory = IDL.Variant({
  'car' : IDL.Null,
  'suv' : IDL.Null,
  'van' : IDL.Null,
  'truck' : IDL.Null,
  'motorcycle' : IDL.Null,
});
export const CreateVehicleInput = IDL.Record({
  'features' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'description' : IDL.Text,
  'pricePerDay' : IDL.Nat,
  'imageUrl' : IDL.Text,
  'category' : VehicleCategory,
});
export const VehicleId = IDL.Nat;
export const VehicleView = IDL.Record({
  'id' : VehicleId,
  'features' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'description' : IDL.Text,
  'available' : IDL.Bool,
  'pricePerDay' : IDL.Nat,
  'imageUrl' : IDL.Text,
  'category' : VehicleCategory,
});
export const BookingId = IDL.Nat;
export const Timestamp = IDL.Int;
export const CreateBookingInput = IDL.Record({
  'dropoffDate' : Timestamp,
  'pickupDate' : Timestamp,
  'vehicleId' : VehicleId,
});
export const BookingStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const BookingView = IDL.Record({
  'id' : BookingId,
  'status' : BookingStatus,
  'referenceNumber' : IDL.Text,
  'dropoffDate' : Timestamp,
  'userId' : IDL.Principal,
  'createdAt' : Timestamp,
  'pickupDate' : Timestamp,
  'totalAmount' : IDL.Nat,
  'vehicleId' : VehicleId,
});
export const BookingResult = IDL.Variant({
  'ok' : BookingView,
  'err' : IDL.Text,
});
export const UpdateVehicleInput = IDL.Record({
  'id' : VehicleId,
  'features' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'description' : IDL.Text,
  'available' : IDL.Bool,
  'pricePerDay' : IDL.Nat,
  'imageUrl' : IDL.Text,
  'category' : VehicleCategory,
});

export const idlService = IDL.Service({
  'addVehicle' : IDL.Func([CreateVehicleInput], [VehicleView], []),
  'cancelBooking' : IDL.Func(
      [BookingId],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'createBooking' : IDL.Func([CreateBookingInput], [BookingResult], []),
  'deleteVehicle' : IDL.Func(
      [VehicleId],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'getVehicle' : IDL.Func([VehicleId], [IDL.Opt(VehicleView)], ['query']),
  'isAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listAllBookings' : IDL.Func([], [IDL.Vec(BookingView)], ['query']),
  'listVehicles' : IDL.Func([], [IDL.Vec(VehicleView)], ['query']),
  'myBookings' : IDL.Func([], [IDL.Vec(BookingView)], ['query']),
  'registerAdmin' : IDL.Func(
      [],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'setVehicleAvailability' : IDL.Func(
      [VehicleId, IDL.Bool],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'updateVehicle' : IDL.Func([UpdateVehicleInput], [VehicleView], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const VehicleCategory = IDL.Variant({
    'car' : IDL.Null,
    'suv' : IDL.Null,
    'van' : IDL.Null,
    'truck' : IDL.Null,
    'motorcycle' : IDL.Null,
  });
  const CreateVehicleInput = IDL.Record({
    'features' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'description' : IDL.Text,
    'pricePerDay' : IDL.Nat,
    'imageUrl' : IDL.Text,
    'category' : VehicleCategory,
  });
  const VehicleId = IDL.Nat;
  const VehicleView = IDL.Record({
    'id' : VehicleId,
    'features' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'description' : IDL.Text,
    'available' : IDL.Bool,
    'pricePerDay' : IDL.Nat,
    'imageUrl' : IDL.Text,
    'category' : VehicleCategory,
  });
  const BookingId = IDL.Nat;
  const Timestamp = IDL.Int;
  const CreateBookingInput = IDL.Record({
    'dropoffDate' : Timestamp,
    'pickupDate' : Timestamp,
    'vehicleId' : VehicleId,
  });
  const BookingStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const BookingView = IDL.Record({
    'id' : BookingId,
    'status' : BookingStatus,
    'referenceNumber' : IDL.Text,
    'dropoffDate' : Timestamp,
    'userId' : IDL.Principal,
    'createdAt' : Timestamp,
    'pickupDate' : Timestamp,
    'totalAmount' : IDL.Nat,
    'vehicleId' : VehicleId,
  });
  const BookingResult = IDL.Variant({ 'ok' : BookingView, 'err' : IDL.Text });
  const UpdateVehicleInput = IDL.Record({
    'id' : VehicleId,
    'features' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'description' : IDL.Text,
    'available' : IDL.Bool,
    'pricePerDay' : IDL.Nat,
    'imageUrl' : IDL.Text,
    'category' : VehicleCategory,
  });
  
  return IDL.Service({
    'addVehicle' : IDL.Func([CreateVehicleInput], [VehicleView], []),
    'cancelBooking' : IDL.Func(
        [BookingId],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'createBooking' : IDL.Func([CreateBookingInput], [BookingResult], []),
    'deleteVehicle' : IDL.Func(
        [VehicleId],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'getVehicle' : IDL.Func([VehicleId], [IDL.Opt(VehicleView)], ['query']),
    'isAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listAllBookings' : IDL.Func([], [IDL.Vec(BookingView)], ['query']),
    'listVehicles' : IDL.Func([], [IDL.Vec(VehicleView)], ['query']),
    'myBookings' : IDL.Func([], [IDL.Vec(BookingView)], ['query']),
    'registerAdmin' : IDL.Func(
        [],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'setVehicleAvailability' : IDL.Func(
        [VehicleId, IDL.Bool],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'updateVehicle' : IDL.Func([UpdateVehicleInput], [VehicleView], []),
  });
};

export const init = ({ IDL }) => { return []; };