/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface UpdateVehicleInput {
    id: VehicleId;
    features: Array<string>;
    name: string;
    description: string;
    available: boolean;
    pricePerDay: bigint;
    imageUrl: string;
    category: VehicleCategory;
}
export type Timestamp = bigint;
export type VehicleId = bigint;
export interface VehicleView {
    id: VehicleId;
    features: Array<string>;
    name: string;
    description: string;
    available: boolean;
    pricePerDay: bigint;
    imageUrl: string;
    category: VehicleCategory;
}
export interface CreateVehicleInput {
    features: Array<string>;
    name: string;
    description: string;
    pricePerDay: bigint;
    imageUrl: string;
    category: VehicleCategory;
}
export type BookingId = bigint;
export interface CreateBookingInput {
    dropoffDate: Timestamp;
    pickupDate: Timestamp;
    vehicleId: VehicleId;
}
export type BookingResult = {
    __kind__: "ok";
    ok: BookingView;
} | {
    __kind__: "err";
    err: string;
};
export interface BookingView {
    id: BookingId;
    status: BookingStatus;
    referenceNumber: string;
    dropoffDate: Timestamp;
    userId: Principal;
    createdAt: Timestamp;
    pickupDate: Timestamp;
    totalAmount: bigint;
    vehicleId: VehicleId;
}
export enum BookingStatus {
    cancelled = "cancelled",
    confirmed = "confirmed"
}
export enum VehicleCategory {
    car = "car",
    suv = "suv",
    van = "van",
    truck = "truck",
    motorcycle = "motorcycle"
}
export interface backendInterface {
    addVehicle(input: CreateVehicleInput): Promise<VehicleView>;
    cancelBooking(id: BookingId): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    createBooking(input: CreateBookingInput): Promise<BookingResult>;
    deleteVehicle(id: VehicleId): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    getVehicle(id: VehicleId): Promise<VehicleView | null>;
    isAdmin(): Promise<boolean>;
    listAllBookings(): Promise<Array<BookingView>>;
    listVehicles(): Promise<Array<VehicleView>>;
    myBookings(): Promise<Array<BookingView>>;
    registerAdmin(): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    setVehicleAvailability(id: VehicleId, available: boolean): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    updateVehicle(input: UpdateVehicleInput): Promise<VehicleView>;
}
import type { BookingId as _BookingId, BookingResult as _BookingResult, BookingStatus as _BookingStatus, BookingView as _BookingView, CreateVehicleInput as _CreateVehicleInput, Timestamp as _Timestamp, UpdateVehicleInput as _UpdateVehicleInput, VehicleCategory as _VehicleCategory, VehicleId as _VehicleId, VehicleView as _VehicleView } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addVehicle(arg0: CreateVehicleInput): Promise<VehicleView> {
        if (this.processError) {
            try {
                const result = await this.actor.addVehicle(to_candid_CreateVehicleInput_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid_VehicleView_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addVehicle(to_candid_CreateVehicleInput_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid_VehicleView_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async cancelBooking(arg0: BookingId): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.cancelBooking(arg0);
                return from_candid_variant_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cancelBooking(arg0);
            return from_candid_variant_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async createBooking(arg0: CreateBookingInput): Promise<BookingResult> {
        if (this.processError) {
            try {
                const result = await this.actor.createBooking(arg0);
                return from_candid_BookingResult_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBooking(arg0);
            return from_candid_BookingResult_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteVehicle(arg0: VehicleId): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteVehicle(arg0);
                return from_candid_variant_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteVehicle(arg0);
            return from_candid_variant_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVehicle(arg0: VehicleId): Promise<VehicleView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getVehicle(arg0);
                return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVehicle(arg0);
            return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async isAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isAdmin();
            return result;
        }
    }
    async listAllBookings(): Promise<Array<BookingView>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAllBookings();
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAllBookings();
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async listVehicles(): Promise<Array<VehicleView>> {
        if (this.processError) {
            try {
                const result = await this.actor.listVehicles();
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listVehicles();
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async myBookings(): Promise<Array<BookingView>> {
        if (this.processError) {
            try {
                const result = await this.actor.myBookings();
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.myBookings();
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async registerAdmin(): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.registerAdmin();
                return from_candid_variant_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerAdmin();
            return from_candid_variant_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async setVehicleAvailability(arg0: VehicleId, arg1: boolean): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.setVehicleAvailability(arg0, arg1);
                return from_candid_variant_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setVehicleAvailability(arg0, arg1);
            return from_candid_variant_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateVehicle(arg0: UpdateVehicleInput): Promise<VehicleView> {
        if (this.processError) {
            try {
                const result = await this.actor.updateVehicle(to_candid_UpdateVehicleInput_n19(this._uploadFile, this._downloadFile, arg0));
                return from_candid_VehicleView_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateVehicle(to_candid_UpdateVehicleInput_n19(this._uploadFile, this._downloadFile, arg0));
            return from_candid_VehicleView_n5(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_BookingResult_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BookingResult): BookingResult {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_BookingStatus_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BookingStatus): BookingStatus {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_BookingView_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BookingView): BookingView {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_VehicleCategory_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VehicleCategory): VehicleCategory {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_VehicleView_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VehicleView): VehicleView {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_VehicleView]): VehicleView | null {
    return value.length === 0 ? null : from_candid_VehicleView_n5(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _BookingId;
    status: _BookingStatus;
    referenceNumber: string;
    dropoffDate: _Timestamp;
    userId: Principal;
    createdAt: _Timestamp;
    pickupDate: _Timestamp;
    totalAmount: bigint;
    vehicleId: _VehicleId;
}): {
    id: BookingId;
    status: BookingStatus;
    referenceNumber: string;
    dropoffDate: Timestamp;
    userId: Principal;
    createdAt: Timestamp;
    pickupDate: Timestamp;
    totalAmount: bigint;
    vehicleId: VehicleId;
} {
    return {
        id: value.id,
        status: from_candid_BookingStatus_n14(_uploadFile, _downloadFile, value.status),
        referenceNumber: value.referenceNumber,
        dropoffDate: value.dropoffDate,
        userId: value.userId,
        createdAt: value.createdAt,
        pickupDate: value.pickupDate,
        totalAmount: value.totalAmount,
        vehicleId: value.vehicleId
    };
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _VehicleId;
    features: Array<string>;
    name: string;
    description: string;
    available: boolean;
    pricePerDay: bigint;
    imageUrl: string;
    category: _VehicleCategory;
}): {
    id: VehicleId;
    features: Array<string>;
    name: string;
    description: string;
    available: boolean;
    pricePerDay: bigint;
    imageUrl: string;
    category: VehicleCategory;
} {
    return {
        id: value.id,
        features: value.features,
        name: value.name,
        description: value.description,
        available: value.available,
        pricePerDay: value.pricePerDay,
        imageUrl: value.imageUrl,
        category: from_candid_VehicleCategory_n7(_uploadFile, _downloadFile, value.category)
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _BookingView;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: BookingView;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_BookingView_n12(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cancelled: null;
} | {
    confirmed: null;
}): BookingStatus {
    return "cancelled" in value ? BookingStatus.cancelled : "confirmed" in value ? BookingStatus.confirmed : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    car: null;
} | {
    suv: null;
} | {
    van: null;
} | {
    truck: null;
} | {
    motorcycle: null;
}): VehicleCategory {
    return "car" in value ? VehicleCategory.car : "suv" in value ? VehicleCategory.suv : "van" in value ? VehicleCategory.van : "truck" in value ? VehicleCategory.truck : "motorcycle" in value ? VehicleCategory.motorcycle : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_BookingView>): Array<BookingView> {
    return value.map((x)=>from_candid_BookingView_n12(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_VehicleView>): Array<VehicleView> {
    return value.map((x)=>from_candid_VehicleView_n5(_uploadFile, _downloadFile, x));
}
function to_candid_CreateVehicleInput_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateVehicleInput): _CreateVehicleInput {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_UpdateVehicleInput_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateVehicleInput): _UpdateVehicleInput {
    return to_candid_record_n20(_uploadFile, _downloadFile, value);
}
function to_candid_VehicleCategory_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VehicleCategory): _VehicleCategory {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    features: Array<string>;
    name: string;
    description: string;
    pricePerDay: bigint;
    imageUrl: string;
    category: VehicleCategory;
}): {
    features: Array<string>;
    name: string;
    description: string;
    pricePerDay: bigint;
    imageUrl: string;
    category: _VehicleCategory;
} {
    return {
        features: value.features,
        name: value.name,
        description: value.description,
        pricePerDay: value.pricePerDay,
        imageUrl: value.imageUrl,
        category: to_candid_VehicleCategory_n3(_uploadFile, _downloadFile, value.category)
    };
}
function to_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: VehicleId;
    features: Array<string>;
    name: string;
    description: string;
    available: boolean;
    pricePerDay: bigint;
    imageUrl: string;
    category: VehicleCategory;
}): {
    id: _VehicleId;
    features: Array<string>;
    name: string;
    description: string;
    available: boolean;
    pricePerDay: bigint;
    imageUrl: string;
    category: _VehicleCategory;
} {
    return {
        id: value.id,
        features: value.features,
        name: value.name,
        description: value.description,
        available: value.available,
        pricePerDay: value.pricePerDay,
        imageUrl: value.imageUrl,
        category: to_candid_VehicleCategory_n3(_uploadFile, _downloadFile, value.category)
    };
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VehicleCategory): {
    car: null;
} | {
    suv: null;
} | {
    van: null;
} | {
    truck: null;
} | {
    motorcycle: null;
} {
    return value == VehicleCategory.car ? {
        car: null
    } : value == VehicleCategory.suv ? {
        suv: null
    } : value == VehicleCategory.van ? {
        van: null
    } : value == VehicleCategory.truck ? {
        truck: null
    } : value == VehicleCategory.motorcycle ? {
        motorcycle: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
